"""Example: Custom report template.

Shows how to create and use custom HackerOne report templates.
"""

import json
from pathlib import Path
from datetime import datetime, timezone


class CustomReportTemplate:
    """Minimal report template for quick submissions."""

    TEMPLATE = """# {title}

## Summary
{summary}

## Asset
- **URL**: {affected_asset}
- **Program**: {program_handle}
- **Severity**: {severity}
- **Confidence**: {confidence}

## Description
{description}

## Steps to Reproduce
{steps}

## Impact
{impact}

## Evidence
```json
{evidence_json}
```

## Remediation
{remediation}

---
*Generated by H1ScopeAgent | {timestamp}*
*Finding ID: {finding_id}*
"""

    def render(self, finding: dict, program_handle: str) -> str:
        return self.TEMPLATE.format(
            title=finding.get("title", "Untitled"),
            summary=self._generate_summary(finding),
            affected_asset=finding.get("affected_asset", "Unknown"),
            program_handle=program_handle,
            severity=finding.get("estimated_severity", "info").upper(),
            confidence=finding.get("confidence", "low").upper(),
            description=finding.get("candidate_type", "").replace("_", " "),
            steps=self._format_reproduction(finding),
            impact=self._assess_impact(finding),
            evidence_json=json.dumps(finding.get("evidence", {}), indent=2, default=str),
            remediation=self._suggest_remediation(finding),
            timestamp=datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC"),
            finding_id=finding.get("candidate_id", "N/A"),
        )

    def _generate_summary(self, finding: dict) -> str:
        ctype = finding.get("candidate_type", "").replace("_", " ")
        asset = finding.get("affected_asset", "the target")
        return f"A potential {ctype} was identified on {asset} during automated reconnaissance."

    def _format_reproduction(self, finding: dict) -> str:
        steps = [
            f"1. Navigate to {finding.get('affected_asset', 'the target URL')}",
            "2. Observe the response headers and page content",
            "3. Verify the identified issue exists",
        ]
        return "\n".join(steps)

    def _assess_impact(self, finding: dict) -> str:
        severity = finding.get("estimated_severity", "info")
        impacts = {
            "critical": "Full system compromise or data breach possible if confirmed.",
            "high": "Significant impact on confidentiality, integrity, or availability.",
            "medium": "Limited impact requiring specific conditions.",
            "low": "Minor security concern with minimal impact.",
            "info": "No direct security impact; best practice recommendation.",
        }
        return impacts.get(severity, "Impact unknown — requires manual assessment.")

    def _suggest_remediation(self, finding: dict) -> str:
        ctype = finding.get("candidate_type", "")
        remediations = {
            "hsts": "Enable HSTS with max-age=31536000 and includeSubDomains.",
            "csp": "Implement a strict Content-Security-Policy header.",
            "cookies": "Set Secure, HttpOnly, and SameSite=Lax on all cookies.",
        }
        return remediations.get(ctype, "Review and implement appropriate security controls.")


def demo():
    """Generate a sample report."""
    template = CustomReportTemplate()

    sample_finding = {
        "candidate_id": "FND-abc123def456",
        "title": "Missing HTTP Strict Transport Security (HSTS) Header",
        "affected_asset": "https://api.example.com",
        "candidate_type": "hsts",
        "confidence": "high",
        "estimated_severity": "low",
        "evidence": {
            "observation": "HSTS header not present on HTTPS response",
            "header": "Strict-Transport-Security: missing",
        },
    }

    report = template.render(sample_finding, "example-program")

    output_dir = Path("data/examples")
    output_dir.mkdir(parents=True, exist_ok=True)
    output_path = output_dir / "sample_report.md"
    output_path.write_text(report, encoding="utf-8")

    print(report)
    print(f"\nSaved to: {output_path}")


if __name__ == "__main__":
    demo()
