"""HackerOne-style report draft generator.

Converts candidate findings into structured markdown reports
suitable for HackerOne submission, with proper disclaimers and
evidence formatting.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from typing import Any


class ReportGenerator:
    """Generate HackerOne-style report drafts from candidate findings."""

    def generate_report(self, finding: dict[str, Any], program_handle: str) -> dict[str, Any]:
        title = finding.get("title", "Untitled Finding")
        asset = finding.get("affected_asset", "Unknown")
        severity = finding.get("estimated_severity", "info")
        candidate_type = finding.get("candidate_type", "")
        evidence = finding.get("evidence", {})

        severity_description = self._severity_description(severity)
        impact = self._impact(candidate_type, severity)
        remediation = self._remediation(candidate_type)
        reproduction = self._reproduction(candidate_type)
        evidence_formatted = self._format_evidence(evidence)
        screenshot_refs = self._screenshot_refs(finding)
        scope_confirmation = self._scope_confirmation(finding)
        policy_notes = finding.get("policy_notes", "")

        markdown = f"""# {title}

## Summary
This report documents a potential security issue identified during authorized, non-invasive reconnaissance on {asset}.
**Important**: This is a candidate finding that requires manual verification before submission to HackerOne. The issue has not been exploited or confirmed through active testing.

## Affected Asset
- **Asset**: {asset}
- **Program**: {program_handle}
- **Severity (Estimated)**: {severity.upper()} — {severity_description}
- **Confidence**: {finding.get('confidence', 'low').upper()}

## Description
A potential {candidate_type.replace('_', ' ')} was identified during automated reconnaissance of {asset}. The detection was based on passive observation of HTTP headers, page content, and browser metadata.

## Estimated Impact
{impact}

{screenshot_refs}

## Evidence
{evidence_formatted}

## Reproduction Steps (Safe, Non-Invasive)
{reproduction}

## Recommended Remediation
{remediation}

## Scope Confirmation
{scope_confirmation}

## Policy Compliance
- All testing performed was non-invasive and passive
- No forms were submitted
- No exploits were attempted
- No authentication was bypassed
- All reconnaissance was confined to in-scope assets
- Only safe HTTP GET/HEAD requests were made
{policy_notes}

## Manual Verification Required
This finding is a **candidate** and has NOT been verified through active testing. The following would need manual approval:
- Confirming the issue through controlled testing
- Verifying exploitability
- Assessing exact impact
- HackerOne program managers should verify this aligns with program policy

## Discovery Method
- **Tool**: H1ScopeAgent (automated non-invasive reconnaissance)
- **Technique**: {candidate_type.replace('_', ' ')}
- **Authorization**: Authorized HackerOne bug bounty program

## Suggested Remediation
## Additional Notes
- Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')}
- Finding ID: {finding.get('candidate_id', 'N/A')}
- Report generated by H1ScopeAgent — requires human review before submission
"""

        return {
            "finding_id": finding.get("candidate_id", ""),
            "title": title,
            "affected_asset": asset,
            "severity": severity,
            "markdown_body": markdown,
        }

    def _severity_description(self, severity: str) -> str:
        descriptions = {
            "critical": "Critical severity — may allow full system compromise or data breach if confirmed",
            "high": "High severity — potential for significant impact on confidentiality, integrity, or availability",
            "medium": "Medium severity — limited impact or requiring specific conditions",
            "low": "Low severity — minor security concern with minimal impact",
            "info": "Informational — no direct security impact, good practice recommendation",
        }
        return descriptions.get(severity, "Unknown severity")

    def _impact(self, candidate_type: str, severity: str) -> str:
        impacts = {
            "hsts": "Without HSTS, users may be vulnerable to SSL stripping attacks, allowing an attacker to downgrade connections to plain HTTP and intercept traffic.",
            "csp": "Without a Content Security Policy, the application is more vulnerable to XSS attacks, data injection, and other client-side code execution attacks.",
            "x_frame_options": "Without clickjacking protection, an attacker could embed this site in an iframe and trick users into performing unintended actions.",
            "x_content_type_options": "Without nosniff protection, browsers may be tricked into executing files as different MIME types, potentially leading to XSS.",
            "cookies": "Insecure cookies may be transmitted over unencrypted connections or accessed by client-side scripts, leading to session hijacking or data theft.",
            "cors_misconfig": "A misconfigured CORS policy could allow unauthorized domains to make authenticated requests, potentially exposing user data or allowing CSRF attacks.",
            "secret_leakage": "Exposed secrets (API keys, tokens, credentials) in public resources could allow attackers to access protected services, user data, or internal systems.",
            "outdated_tech": "Outdated software versions may contain known, publicly disclosed vulnerabilities that attackers can exploit.",
            "source_maps": "Exposed source maps reveal original source code, making it easier for attackers to understand application logic and find vulnerabilities.",
            "robots_sensitive": "Sensitive paths disclosed in robots.txt reveal internal application structure, aiding reconnaissance and targeted attacks.",
            "redirect_params": "Open redirect vulnerabilities can be used in phishing attacks, redirecting users to malicious sites while appearing to come from the trusted domain.",
        }
        for key, desc in impacts.items():
            if key in candidate_type.lower():
                return desc

        return "This finding may indicate a security weakness that could be leveraged by attackers if confirmed through active testing."

    def _remediation(self, candidate_type: str) -> str:
        remediations = {
            "hsts": "1. Add `Strict-Transport-Security: max-age=31536000; includeSubDomains; preload` to all HTTPS responses.\n2. Submit the domain to the HSTS preload list.\n3. Ensure all subdomains support HTTPS.",
            "csp": "1. Implement a strict Content-Security-Policy header.\n2. Start with `Content-Security-Policy: default-src 'self'; script-src 'self'`.\n3. Avoid unsafe-inline and unsafe-eval; use nonces or hashes.\n4. Test with `Content-Security-Policy-Report-Only` before enforcing.",
            "x_frame_options": "1. Add `X-Frame-Options: DENY` or `X-Frame-Options: SAMEORIGIN`.\n2. Alternatively, use CSP `frame-ancestors 'none'` or `frame-ancestors 'self'`.\n3. Consider both headers for compatibility.",
            "x_content_type_options": 'Add `X-Content-Type-Options: nosniff` to all responses to prevent MIME type sniffing.',
            "cookies": "1. Set `Secure` flag on all cookies to ensure HTTPS-only transmission.\n2. Set `HttpOnly` flag to prevent JavaScript access.\n3. Set `SameSite=Lax` or `SameSite=Strict` to prevent CSRF.\n4. Consider cookie prefixes `__Secure-` and `__Host-`.",
            "cors_misconfig": "1. Restrict `Access-Control-Allow-Origin` to specific trusted domains.\n2. Never use wildcard `*` with `Access-Control-Allow-Credentials: true`.\n3. Validate the `Origin` header server-side.\n4. Only allow specific methods and headers.",
            "secret_leakage": "1. Immediately remove exposed secrets from all public resources.\n2. Rotate all exposed credentials and API keys.\n3. Implement code review processes to prevent secret leakage.\n4. Use environment variables or secret management services.\n5. Add .gitignore rules and pre-commit hooks for secret detection.",
            "outdated_tech": "1. Update all software components to supported versions.\n2. Implement regular patch management.\n3. Monitor vendor security advisories.\n4. Use dependency scanning tools in CI/CD.",
            "source_maps": "1. Remove source maps from production deployments.\n2. If source maps are needed for error tracking, serve them from a restricted path.\n3. Configure build tools to not generate source maps for production.",
            "robots_sensitive": "1. Review robots.txt for sensitive path disclosure.\n2. Remove entries that reveal internal application structure.\n3. Use proper access controls instead of relying on robots.txt for security.",
        }
        for key, rem in remediations.items():
            if key in candidate_type.lower():
                return rem
        return "Review and implement appropriate security controls based on manual verification results."

    def _reproduction(self, candidate_type: str) -> str:
        steps = [
            "**All steps below are safe, passive, and non-invasive:**\n",
        ]
        if "hsts" in candidate_type.lower() or "csp" in candidate_type.lower() or "cookies" in candidate_type.lower():
            steps.append("1. Open browser developer tools (F12)")
            steps.append("2. Navigate to the affected URL")
            steps.append("3. Inspect the Network tab → Response Headers")
            steps.append("4. Verify the absence/weakness of the relevant security header")
        elif "secret" in candidate_type.lower():
            steps.append("1. View the page source (Ctrl+U)")
            steps.append("2. Search for API key patterns, tokens, or credentials")
            steps.append("3. Note: observed secrets should NOT be tested — rotate them immediately")
        else:
            steps.append("1. Inspect HTTP response headers using `curl -I <URL>`")
            steps.append("2. Review page source for indicators")
            steps.append("3. Validate against security best practices")
        return "\n".join(steps)

    def _format_evidence(self, evidence: dict) -> str:
        if not evidence:
            return "No evidence collected — manual inspection required"

        lines = []
        for k, v in evidence.items():
            val_str = json.dumps(v, default=str, indent=2) if isinstance(v, (list, dict)) else str(v)
            lines.append(f"### {k.replace('_', ' ').title()}")
            lines.append("```")
            lines.append(val_str[:1500])
            lines.append("```")
            lines.append("")

        return "\n".join(lines[:40])

    def _screenshot_refs(self, finding: dict) -> str:
        ss = finding.get("screenshot_path", "")
        if not ss:
            return ""
        return f"## Screenshot\nScreenshot captured during reconnaissance: `{ss}`\n"

    def _scope_confirmation(self, finding: dict) -> str:
        asset = finding.get("affected_asset", "Unknown")
        return f"""- **Asset**: `{asset}`
- **Verification**: Confirmed in-scope via HackerOne structured scopes
- **Method**: Passive browser reconnaissance only
- **Out-of-scope assets**: Not targeted"""
